#!/bin/bash
# chkconfig: 345 20 80
# description: filebeat
#
########################################################
#
#    脚本名称: filebeat.sh
#
#    功    能: 启动、关停 服务
#
#    用    法: bash filebeat.sh [<stop>|<start>|<restart>]
#
#    作    者: JerryHan
#
#    日    期: 2019/08/13
#
########################################################
#

_HELP()
{
    echo
    grep -w "^#    用    法:" < "$0" | cut -c6-
    exit 1
}

_START(){
    pgrep -f "${HOME_FILEBEAT}/filebeat" &>/dev/null || exec nohup ${HOME_FILEBEAT}/filebeat -c ${HOME_FILEBEAT}/filebeat.yml -e &>/dev/null &
}

_STOP(){
    pgrep -f "${HOME_FILEBEAT}/filebeat" &>/dev/null && pgrep -f "${HOME_FILEBEAT}/filebeat" | xargs kill -9
}

readonly HOME_FILEBEAT="/usr/local/filebeat"

case ${1} in

    "start")
        _START
        ;;

    "stop")
        _STOP
        ;;

    "restart")
        _STOP
        sleep 2
        _START
        ;;

    "")
        _HELP
        ;;

    *)
        { echo "Invalid Parameter" 2>&1;exit 1; }
        ;;

esac
# (END)